default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: seu_portfolio_desenvolvimento_db
  username: livan

test:
  <<: *default
  database: seu_portfolio_teste_db
  username: livan

production:
  <<: *default
  database: seu_portfolio_producao_db
  username: portfolio_user
  password: h@Rp1@78579467
  host: 127.0.0.1
  port: 5433
